- name: "Play to configure website assets on the webnode"
  hosts: web-servers
  tasks:
    - 
      command: sudo yum update -y
    - 
      name: Installing httpd
      yum:
        name: httpd
        state: present

    - 
      name: Installing git
      yum:
        name: git
        state: present

    - command: sudo rm -rf /tmp/static-test-website

    - git:
        repo: 'https://github.com/nehanikam/static-test-website.git'
        dest: /tmp/static-test-website
        clone: yes
        update: yes

    - name: copy html file
      shell: sudo cp -uR /tmp/static-test-website/src/* /var/www/html 

    -
      name: Start httpd
      service:
        name: httpd
        state: restarted